#!/bin/sh

do_help()
{
cat << EOF
Usage:
$0 [start|stop|status|restart|add|remove] /path/to/service

Options:
start	Start a service.
stop	Stop a running service.
restart	Stop, then start a previously running service.
status	Report the status of the given service.
add	Adds a service directory to /etc/service via soft linking.
remove	Removes a service from /etc/service by removing the soft link.
EOF
}
case $1 in
	start|restart) sv up /etc/service/$(basename $2);;
	stop) sv down /etc/service/$(basename $2);;
	status) sv $1 /etc/service/$(basename $2);;
	add) ln -s $2 /etc/service/$(basename $2);;
	remove) rm -rf /etc/service/$(basename $2);;
	*) do_help;exit;;
esac
