#!/bin/sh
echo "Rocketbox init v0.2alpha"
echo "Starting up..."
dmesg -n 1
echo "Mounting filesystems..."
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev
mount -t devpts none /dev/pts
mount -t tmpfs none /tmp -o mode=1777
echo "Starting mdev hotplug..."
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s
echo "Synchronizing clock..."
hwclock -u -s
echo "Mounting all from /etc/fstab..."
mount -a
echo "Read and write permissions..."
mount -o remount,rw /
echo "Setting hostname..."
hostname -F /etc/hostname
echo "Setting up networking..."
for DEVICE in /sys/class/net/* ; do
  echo "Found network device ${DEVICE##*/}"
  ip link set ${DEVICE##*/} up
  [ ${DEVICE##*/} != lo ] && udhcpc -b -i ${DEVICE##*/} -s /etc/rc.dhcp
done
echo "Starting services and userspace..."
exec /sbin/init
