#!/bin/sh

rescue_shell() {
	echo -e "\e[1;31m(FAIL)\e[0m System could not be initiated! Dropping to Emergency Shell!" 
	exec sh
}

echo -e "\e[1mRocketbox init v0.2alpha\e[0m"
echo "Starting up..."
dmesg -n 1
echo "Mounting filesystems..."
mount -t proc none /proc || rescue_shell
mount -t sysfs none /sys || rescue_shell
mount -t tmpfs /tmp /tmp || rescue_shell
mkdir /dev/pts
mkdir /dev/shm
mount -t devpts none /dev/pts
mount -t tmpfs none /dev/shm
echo "Starting mdev hotplug..."
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s
echo "Synchronizing clock..."
hwclock -u -s
echo "Read and only permissions..."
mount -o remount,ro /
if [ -x /sbin/fsck ]; then
  echo "Starting fsck for local filesystems."
	fsck -A -C -R -T -t nonfs,nosmbfs
	if [ "$?" -gt 2 ]; then
		echo "WARNING: Errors found while checking filesystems."
		echo "You can login as root now, the system will reboot after logout."
		sulogin
		reboot
	elif [ "$?" = "2" ]; then
		echo "NOTICE: System needs to be rebooted now."
		sleep 1
		reboot
	else
		echo -n "Checking local filesystems: "
		#check_status
	fi
fi
echo "Read and write permissions..."
mount -o remount,rw / || rescue_shell
echo "Activating swap..."
swapon -a
echo "Mounting all from /etc/fstab..."
mount -a
echo "Setting hostname..."
hostname -F /etc/hostname
echo "Setting up networking..."
for DEVICE in /sys/class/net/* ; do
  echo "Found network device ${DEVICE##*/}"
  ip link set ${DEVICE##*/} up
  [ ${DEVICE##*/} != lo ] && udhcpc -b -i ${DEVICE##*/} -s /etc/rc.dhcp
done
echo "Starting services and userspace..."
exec /sbin/init
